### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by meveleper**
Thank you for submitting a pull request to the WebGoat!

### CODE REVIEW

**Review by thyldrm — CHANGES_REQUESTED** [review]
you have vuln

**Review by thyldrm — CHANGES_REQUESTED** [review]
no

**Review by thyldrm — CHANGES_REQUESTED** [review]
cmon

**Review by thyldrm — CHANGES_REQUESTED** [review]
hi

**Review by thyldrm — CHANGES_REQUESTED** [review]
sdf

**Review by thyldrm — CHANGES_REQUESTED** [review]
[{"a":"hi","b":1}]

**Review by meveleper — COMMENTED** [review]
`{
a:1,
b:2}`

**Review by thyldrm — CHANGES_REQUESTED** [review]
[{"a":"hi","b":1}]

**Pull request closed without merging**
